name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: windows11
    

    steps:
    # Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Se connecter à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construire l’image Docker
    - name: Build Docker image
      run: |
        docker build -t votre_utilisateur/nom_projet:latest .

    # Pousser l’image Docker sur Docker Hub
    - name: Push Docker image
      run: |
        docker push votre_utilisateur/nom_projet:latest
